const PASSWORD = '2026';
const cases = [
{n:1,t:'Fáscia do braço e compartimentos',c:'Durante uma prática de dissecação do membro superior, os estudantes observam uma estrutura fibrosa profunda envolvendo completamente os músculos do braço. Ao abrir essa estrutura, identificam-se compartimentos musculares anterior e posterior separados por septos.',q:'Qual estrutura está sendo observada, quais estruturas ela forma e qual sua importância anatômica?',a:'A estrutura observada é a fáscia do braço.\n\nEla forma:\n• septo intermuscular medial;\n• septo intermuscular lateral;\n• compartimentos anterior e posterior do braço.\n\nFunções:\n• envolver e organizar grupos musculares;\n• separar músculos por função;\n• permitir passagem neurovascular;\n• auxiliar na contenção e estabilização muscular.'},
{n:2,t:'Compartimento anterior do braço',c:'Durante análise funcional do braço, um pesquisador observa um indivíduo realizando flexão do antebraço repetidamente.',q:'Quais músculos pertencem principalmente ao compartimento anterior do braço e quais suas funções?',a:'Músculos:\n• braquial;\n• bíceps braquial;\n• coracobraquial.\n\nFunções:\n• flexão do antebraço;\n• supinação do antebraço pelo bíceps;\n• flexão e adução do braço;\n• estabilização do ombro.'},
{n:3,t:'Compartimento posterior do braço',c:'Após trauma posterior do braço, um atleta apresenta dificuldade importante para extensão do cotovelo.',q:'Qual compartimento muscular provavelmente foi afetado, qual músculo principal está envolvido e qual sua função?',a:'O compartimento afetado é o compartimento posterior do braço.\n\nMúsculo principal:\n• tríceps braquial.\n\nFunções:\n• extensão do antebraço;\n• estabilização do cotovelo;\n• auxílio na extensão do braço.'},
{n:4,t:'Membrana interóssea do antebraço',c:'Durante dissecação do antebraço, estudantes observam uma membrana fibrosa entre rádio e ulna.',q:'Qual estrutura está sendo observada e qual sua importância anatômica?',a:'A estrutura observada é a membrana interóssea do antebraço.\n\nFunções:\n• unir rádio e ulna;\n• estabilizar o antebraço;\n• servir de inserção muscular;\n• distribuir forças mecânicas.'},
{n:5,t:'Aponeurose palmar',c:'Durante análise funcional da mão, um indivíduo apresenta dificuldade para manter objetos firmemente segurados.',q:'Qual estrutura fascial da palma auxilia na estabilidade da mão e qual sua função?',a:'A estrutura é a aponeurose palmar.\n\nFunções:\n• proteção de estruturas profundas;\n• estabilização da pele palmar;\n• auxílio na preensão manual;\n• distribuição de forças.'},
{n:6,t:'Retináculo dos flexores',c:'Em uma prática anatômica, alunos observam uma faixa fibrosa espessa localizada anteriormente ao punho envolvendo tendões flexores.',q:'Qual estrutura está sendo observada e qual sua função?',a:'A estrutura observada é o retináculo dos músculos flexores, também chamado de ligamento carpal transverso.\n\nFunções:\n• manter tendões flexores posicionados;\n• evitar arqueamento tendíneo;\n• formar o túnel do carpo;\n• estabilizar movimentos do punho.'},
{n:7,t:'Retináculo dos extensores',c:'Durante movimentos repetitivos do punho, um estudante apresenta dor dorsal associada aos tendões extensores.',q:'Qual estrutura anatômica mantém esses tendões organizados dorsalmente?',a:'A estrutura é o retináculo dos músculos extensores.\n\nFunções:\n• estabilizar tendões extensores;\n• evitar deslocamento tendíneo;\n• organizar compartimentos extensores.'},
{n:8,t:'Fáscia lata',c:'Durante uma dissecação da coxa, os alunos observam espessa fáscia envolvendo toda a musculatura do membro inferior.',q:'Qual estrutura está sendo observada e quais suas funções?',a:'A estrutura observada é a fáscia lata.\n\nFunções:\n• envolver musculatura da coxa;\n• formar septos intermusculares;\n• organizar compartimentos musculares;\n• auxiliar na estabilização do membro inferior.'},
{n:9,t:'Compartimento anterior da coxa',c:'Durante análise anatômica da coxa, estudantes identificam compartimento muscular responsável principalmente pela extensão do joelho.',q:'Qual compartimento está sendo observado, quais músculos o compõem e quais suas funções?',a:'O compartimento observado é o compartimento anterior da coxa.\n\nMúsculos:\n• quadríceps femoral;\n• sartório.\n\nFunções:\n• extensão do joelho;\n• flexão da coxa;\n• estabilização da marcha.'},
{n:10,t:'Compartimento posterior da coxa',c:'Após lesão muscular posterior da coxa, um indivíduo apresenta dificuldade para flexão do joelho.',q:'Qual compartimento foi afetado e quais músculos estão envolvidos?',a:'O compartimento afetado é o compartimento posterior da coxa.\n\nMúsculos:\n• bíceps femoral;\n• semitendinoso;\n• semimembranoso.\n\nFunções:\n• flexão do joelho;\n• extensão da coxa;\n• estabilização pélvica.'},
{n:11,t:'Compartimento anterior da perna',c:'Durante uma prática funcional, um indivíduo realiza dorsiflexão repetida do pé.',q:'Qual compartimento da perna está envolvido, quais músculos participam e quais suas funções?',a:'O compartimento envolvido é o compartimento anterior da perna.\n\nMúsculos:\n• tibial anterior;\n• extensores dos dedos.\n\nFunções:\n• dorsiflexão;\n• extensão dos dedos;\n• estabilização durante marcha.'},
{n:12,t:'Compartimento posterior da perna',c:'Um atleta apresenta dificuldade importante para realizar flexão plantar após trauma na panturrilha.',q:'Qual compartimento muscular foi provavelmente lesionado e quais músculos principais o compõem?',a:'O compartimento lesionado é o compartimento posterior da perna.\n\nMúsculos:\n• gastrocnêmio;\n• sóleo;\n• plantar.\n\nFunções:\n• flexão plantar;\n• impulsão corporal;\n• auxílio no retorno venoso.'},
{n:13,t:'Manguito rotador',c:'Durante dissecação do ombro, estudantes observam músculos estabilizadores profundos envolvendo a cabeça do úmero.',q:'Qual grupo muscular está sendo observado e quais suas funções?',a:'O grupo muscular corresponde ao manguito rotador.\n\nMúsculos:\n• supraespinal;\n• infraespinal;\n• redondo menor;\n• subescapular.\n\nFunções:\n• estabilização do ombro;\n• rotação medial e lateral;\n• auxílio na abdução.'},
{n:14,t:'Músculos intercostais',c:'Durante prática anatômica do tórax, alunos observam músculos localizados entre as costelas.',q:'Quais músculos estão sendo observados e quais suas funções?',a:'Os músculos observados são os músculos intercostais.\n\nFunções:\n• movimentação das costelas;\n• auxílio respiratório;\n• estabilização da parede torácica.'},
{n:15,t:'Serrátil anterior',c:'Um indivíduo apresenta dificuldade para manter a escápula aderida à parede torácica.',q:'Qual músculo provavelmente está comprometido e quais suas funções?',a:'O músculo comprometido é o serrátil anterior.\n\nFunções:\n• protrusão da escápula;\n• estabilização escapular;\n• auxílio na rotação da escápula.'},
{n:16,t:'Parede abdominal',c:'Durante análise da parede abdominal, estudantes identificam músculos organizados em camadas.',q:'Quais músculos compõem essa parede e quais suas funções gerais?',a:'Músculos:\n• oblíquo externo;\n• oblíquo interno;\n• transverso do abdome;\n• reto do abdome.\n\nFunções:\n• compressão abdominal;\n• estabilização do tronco;\n• flexão e rotação do tronco;\n• auxílio respiratório.'},
{n:17,t:'Eretor da espinha',c:'Durante estudo anatômico da coluna vertebral, um pesquisador observa musculatura profunda organizada longitudinalmente.',q:'Qual grupo muscular está sendo observado e quais suas funções?',a:'O grupo corresponde ao eretor da espinha.\n\nFunções:\n• extensão da coluna;\n• manutenção postural;\n• estabilização vertebral;\n• controle de movimentos do tronco.'},
{n:18,t:'Interósseos da mão',c:'Durante prática da mão, estudantes observam pequenos músculos localizados entre os metacarpos.',q:'Quais músculos são esses e quais suas funções?',a:'Os músculos são os interósseos da mão.\n\nFunções:\n• abdução dos dedos;\n• adução dos dedos;\n• estabilização digital;\n• auxílio na motricidade fina.'},
{n:19,t:'Musculatura tenar',c:'Durante análise funcional do polegar, observa-se dificuldade para oposição.',q:'Qual grupo muscular está relacionado a esse movimento e quais suas funções?',a:'O grupo muscular corresponde à musculatura tenar.\n\nFunções:\n• oposição do polegar;\n• flexão do polegar;\n• abdução do polegar;\n• precisão manual.'},
{n:20,t:'Glúteo médio e mínimo',c:'Durante dissecação da região glútea, estudantes observam músculos profundos responsáveis por estabilização da pelve durante a marcha.',q:'Quais músculos estão envolvidos e quais suas funções?',a:'Músculos:\n• glúteo médio;\n• glúteo mínimo.\n\nFunções:\n• abdução da coxa;\n• estabilização pélvica;\n• manutenção do equilíbrio durante marcha.'}
];
let uploadedFiles=[];
function unlockApp(){const pass=document.getElementById('password').value.trim();if(pass===PASSWORD){document.getElementById('lockScreen').classList.add('hidden');document.getElementById('app').classList.remove('hidden');localStorage.setItem('muscularUnlocked','yes');renderCards();registerSW();}else{document.getElementById('error').textContent='Código incorreto. Tente novamente.'}}
window.addEventListener('load',()=>{if(localStorage.getItem('muscularUnlocked')==='yes'){document.getElementById('lockScreen').classList.add('hidden');document.getElementById('app').classList.remove('hidden');renderCards();registerSW();}document.getElementById('teacherNotes').value=localStorage.getItem('teacherNotes')||''});
function renderCards(){
  const term=(document.getElementById('search')?.value||'').toLowerCase();
  const list=cases.filter(x=>(x.t+x.c+x.q).toLowerCase().includes(term));
  document.getElementById('count').textContent=`${list.length} de ${cases.length} casos exibidos`;
  document.getElementById('cards').innerHTML=list.map(item=>`
    <article class="card">
      <div class="case-number"><strong>CASO ${item.n}</strong><span class="tag">Macroscopia</span></div>
      <h3>${item.t}</h3>
      <p class="case-text">${item.c}</p>
      <div class="qa">
        <button onclick="toggle('q${item.n}')">Ver pergunta</button>
        <div id="q${item.n}" class="qa-content hidden">${item.q}</div>
        <button class="answer-btn" onclick="askAnswerPassword(${item.n})">🔒 Liberar resposta</button>
        <div id="a${item.n}" class="qa-content answer-content hidden"></div>
      </div>
    </article>`).join('');
}
function toggle(id){document.getElementById(id).classList.toggle('hidden')}
function askAnswerPassword(n){
  const pass = prompt('Digite o código da professora para liberar a resposta:');
  if(pass === PASSWORD){
    const item = cases.find(c => c.n === n);
    const box = document.getElementById('a'+n);
    box.textContent = item.a;
    box.classList.remove('hidden');
  } else if(pass !== null){
    alert('Código incorreto. A resposta continuará oculta.');
  }
}
function openNotes(){document.getElementById('notesBox').classList.toggle('hidden')}
function saveNotes(){localStorage.setItem('teacherNotes',document.getElementById('teacherNotes').value);alert('Anotações salvas no navegador.')}
function handleFiles(e){uploadedFiles=[...uploadedFiles,...Array.from(e.target.files)];document.getElementById('filesBox').classList.remove('hidden');document.getElementById('fileCount').textContent=`${uploadedFiles.length} arquivo(s) incluído(s)`;document.getElementById('fileList').innerHTML=uploadedFiles.map(f=>`<li>${f.name} — ${(f.size/1024).toFixed(1)} KB</li>`).join('')}
function expandQuestionsOnly(){document.querySelectorAll('[id^=q]').forEach(el=>el.classList.remove('hidden'));document.querySelectorAll('.answer-content').forEach(el=>{el.textContent='';el.classList.add('hidden')})}
function generatePDF(){expandQuestionsOnly();const notes=document.getElementById('teacherNotes').value.trim();let old=document.getElementById('printNotes');if(old)old.remove();if(notes){const div=document.createElement('div');div.id='printNotes';div.className='note-print';div.innerHTML='<h2>Anotações da professora</h2>'+notes.replace(/\n/g,'<br>');document.getElementById('pdfArea').prepend(div)}const opt={margin:0.45,filename:'casos-clinicos-sistema-muscular.pdf',image:{type:'jpeg',quality:0.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'in',format:'a4',orientation:'portrait'}};html2pdf().set(opt).from(document.getElementById('pdfArea')).save()}
function registerSW(){if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}}
